### ISSUE TITLE
Close Modal?

### ISSUE THREAD

**Issue by petertait** [davidmfoley/react-router-modal#2]
Firstly, great project and thanks!

I am trying to find the easiest way to hide a modal after opening. May be worth adding this to the documentation, currently I only see clicking the backdrop as the only easy way.

**Comment by 01Kuzma** [comment]
How have you solved this?

**Comment by events-jonas-chrisw** [comment]
I wondered how you did this too?

**Comment by petertait** [comment]
Sorry for delayed response...

I decided to just use react-router by itself without this package in the end. Using a Link to a Route which contained the Modal style component.
