### ISSUE TITLE
Add support for W3 modal accessibility guidelines 

### ISSUE THREAD

**Issue by Leapfrognz** [davidmfoley/react-router-modal#20]
Improve accessibility of the modal as per https://www.w3.org/TR/wai-aria-practices-1.1/#dialog_modal
or, allow us to define custom markup which should help with things like adding aria-modal="true" to the container

**Comment by davidmfoley** [comment]
@Leapfrognz v1.5.0 has support for: role=

**Comment by davidmfoley** [comment]
Sorry this took six months for me to get to. Let me know if there are other improvements to make here for your use case -- I'd be happy to put in some more work here. Thanks.
