### ISSUE TITLE
Use React Portals

### ISSUE THREAD

**Issue by sibelius** [davidmfoley/react-router-modal#22]
React Portals solves how to render a Modal on top of every component

**Comment by davidmfoley** [comment]
I want to continue to support react 15 for now (since react-router-dom still does). When I drop support for v15, portals would be a good solution.

**Comment by davidmfoley** [comment]
From version 2.0, react-router-modal will use portals, which means:
1. react 16.3 context will work correctly. 
2. react & react-dom version 16.3 or higher will be required
2.0.0-rc1 is out now.
