### ISSUE TITLE
Implement boostrap style and animation

### ISSUE THREAD

**Issue by tamanhquyen** [davidmfoley/react-router-modal#23]
Hi,
I want implement like bootstrap 3 style please help me how to use it.

Thanks.

**Comment by davidmfoley** [comment]
Hello.

You can customize the styling of modals using the various class name properties on `ModalContainer` (applies to all modals) or by setting the properties on `Modal`, `ModalLink`, or `ModalRoute`. Then it is up to you to create CSS that implements the styles for those class names. The included CSS is a very basic starting point -- https://github.com/davidmfoley/react-router-modal/blob/master/css/react-router-modal.css
