### ISSUE TITLE
Once modal is closed the previous URL parameter is reset

### ISSUE THREAD

**Issue by 01Kuzma** [davidmfoley/react-router-modal#8]
Hi there!
I've made a simple routing system which handles the language param in a URL.
So if I type `website.com/xx`  - > the appropriate language will be loaded.
`website.com` will load a default language. Pretty straightforward logic.

If I type `website.com/en/modal1` the `modal1` will be opened with English translation, what is good,
But the problem comes when I close the modal. The URL `website.com/en/modal1` is reset to `website.com` without language parameter.

Is there a way to keep the URL parameter once the modal will be closed?
Or it should be a new feature?

Thanks!

**Comment by rscotten** [comment]
maybe set `parentPath='website.com/en'` in the `Modal` or `ModalRoute` component?
